config/routes.rb
NovaHeraSolar::Application.routes.draw do
  root 'welcomes#index'
  devise_for :users
  resources :welcomes, only: [:index]

  namespace :admin do
    root 'welcomes#index'
    resources :products
    resources :accounts
    resources :welcomes, only: [:index]
    resources :budgets
  end
end

app/models/account.rb
class Account < ActiveRecord::Base
  has_one :address
  belongs_to :budget


  STATES = [
    ["AC - Acre", "AC"],
    ["AL - Alagoas", "AL"],
    ["AM - Amazonas", "AM"],
    ["AP - Amapá", "AP"],
    ["BA - Bahia", "BA"],
    ["CE - Ceara", "CE"],
    ["DF - Distrito Federal", "DF"],
    ["ES - Espírito Santo", "ES"],
    ["GO - Goiás", "GO"],
    ["MA - Maranhão", "MA"],
    ["MG - Minas Gerais", "MG"],
    ["MS - Mato Grosso do Sul", "MS"],
    ["MT - Mato Grosso", "MT"],
    ["PA - Pará", "PA"],
    ["PB - Paraíba", "PB"],
    ["PE - Pernambuco", "PE"],
    ["PI - Piauí", "PI"],
    ["PR - Paraná", "PR"],
    ["RJ - Rio de Janeiro", "RJ"],
    ["RN - Rio Grande do Norte", "RN"],
    ["RO - Rondônia", "RO"],
    ["RR - Roraima", "RR"],
    ["RS - Rio Grande do Sul", "RS"],
    ["SC - Santa Catarina", "SC"],
    ["SE - Sergipe", "SE"],
    ["SP - São Paulo", "SP"],
    ["TO - Tocantins", "TO"]
  ]

end

app/models/address.rb
class Address < ActiveRecord::Base
  belongs_to :account

  def to_sentence
    [street, number, city, state].compact.join ", "
  end
end

app/models/budget.rb
class Budget < ActiveRecord::Base
  belongs_to :account
  has_many :budget_items

  accepts_nested_attributes_for :budget_items, reject_if: :all_blank, allow_destroy: true

  before_save :update_total

  private
    def update_total
      self.balance_total = budget_items.map(&:calc_sub_total).sum
    end
end

app/models/budget_item.rb
class BudgetItem < ActiveRecord::Base
  belongs_to :budget
  belongs_to :product

  def calc_sub_total
    amount * sub_total_price
  end
end

app/models/category.rb
class Category < ActiveRecord::Base
  belongs_to :product

  validates :name, presence: true
end

app/models/product.rb
class Product < ActiveRecord::Base
  belongs_to :category
  has_many :budget_items

  validates :name, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/admin/accounts_controller.rb
class Admin::AccountsController < Admin::ApplicationController
  before_action :authenticate_user!
  before_action :set_account, only: [:edit, :update, :destroy]

  def index
    @accounts = Account.all
  end

  def new
    @account = Account.new
  end

  def create
    @account = Account.new(account_params)
    @address = Address.new(address_params)
    @account.address = @address
      if @account.save
        flash[:notice] = 'Conta criada com sucesso!'
        redirect_to admin_accounts_path
      else
        redirect_to new_admin_account_path
      end
  end

  def update
    @account = Account.find(params[:id])
    @account.update_attributes(account_params)
      if @account.save
        flash[:notice] = 'Conta editada com sucesso!'
        redirect_to admin_accounts_path
      else
        redirect_to edit_admin_account_path(@account)
      end
  end

  def destroy
    @account.destroy
  end

  private
    def set_account
      @account = Account.find(params[:id])
    end

    def account_params
      params.require(:account).permit(:name, :cpf, :cnpj, :rg, :email, :phone, :cell, :address )
    end

    def address_params
      params.require(:address).permit(:kind, :street, :number, :complement, :district, :zip_code, :city, :state )
    end
end

app/controllers/admin/application_controller.rb
class Admin::ApplicationController < ApplicationController
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/admin/budgets_controller.rb
class Admin::BudgetsController < Admin::ApplicationController
  before_action :authenticate_user!
  before_action :set_budget, only: [:show, :edit, :update, :destroy]

  def index
    @budgets = Budget.all
  end

  def new
    @budget = Budget.new
  end

  def create
    @budget =  Budget.new(budget_params)

    if @budget.save
      redirect_to admin_budgets_path
    end

  end

  private
    def set_budget
      @budget = Budget.find(params[:id])
    end

    def budget_params
      params.require(:budget).permit(:account_id, :media_kw, :balance_total, budget_items_attributes: [:product_id, :amount, :sub_total_price])
    end


end

app/controllers/admin/products_controller.rb
class Admin::ProductsController < Admin::ApplicationController
  before_action :authenticate_user!
  before_action :set_product, only: [:show, :edit, :update, :destroy]

  def index
    @products = Product.all
  end

  def show

  end

  def new
    @product = Product.new
    @categories = Category.all
  end

  def edit
    @categories = Category.all
  end

  def create
    @product = Product.new(product_params)
      if @product.save
        flash[:notice] = 'Produdo criado com sucesso!'
        redirect_to admin_products_path
      else
        redirect_to new_admin_product_path
      end
  end

  def update
    @product = Product.find(params[:id])
    @product.update_attributes(product_params)
      if @product.save
        flash[:notice] = 'Produto editado com sucesso!'
        redirect_to admin_products_path
      else
        redirect_to edit_admin_product_path(@product)
      end
  end

  def destroy
    @product.destroy
  end

  private
    def set_product
      @product = Product.find(params[:id])
    end

    def product_params
      params.require(:product).permit(:name, :description, :number_references, :category_id, :balance)
    end
end

app/controllers/admin/welcomes_controller.rb
class Admin::WelcomesController < Admin::ApplicationController
  before_action :authenticate_user!
  
  def index
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController

  private

  def sign_up_params
    params.require(:user).permit(:name, :admin, :email, :password, :password_confirmation)
  end

  def account_update_params
    params.require(:user).permit(:name, :admin, :email, :password, :password_confirmation, :current_password)
  end
end

app/controllers/welcomes_controller.rb
class WelcomesController < ApplicationController

  def index
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/admin/accounts/_form.html.erb
<%= simple_form_for([:admin, @account], wrapper: :horizontal_input_group,
        wrapper_mappings: {
          check_boxes: :horizontal_radio_and_checkboxes
        }) do |f| %>
  <% if @account.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@account.errors.count, "error") %> prohibited this account from being saved:</h2>

      <ul>
      <% @account.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-inputs">
    <%= f.input :name, wrapper: :vertical_input_group, hint: "Obrigatório", label: false  do %>
        <span class="input-group-addon">Nome</span>
      <%= f.input_field :name, class: "form-control" %>
    <% end %>
  </div>
  <div class="form-inputs">
    <%= f.input :cpf, wrapper: :vertical_input_group, label: false  do %>
        <span class="input-group-addon">CPF</span>
      <%= f.input_field :cpf, class: "form-control icpf" %>
    <% end %>
  </div>
  <div class="form-inputs">
    <%= f.input :cnpj, wrapper: :vertical_input_group, label: false  do %>
        <span class="input-group-addon">CNPJ</span>
      <%= f.input_field :cnpj, class: "form-control icnpj" %>
    <% end %>
  </div>
  <div class="form-inputs">
    <%= f.input :rg, wrapper: :vertical_input_group, label: false  do %>
        <span class="input-group-addon">RG</span>
      <%= f.input_field :rg, class: "form-control" %>
    <% end %>
  </div>
  <div class="form-inputs">
    <%= f.input :email, wrapper: :vertical_input_group, label: false  do %>
        <span class="input-group-addon">E-mail</span>
      <%= f.input_field :email, class: "form-control" %>
    <% end %>
  </div>
  <div class="form-inputs">
    <%= f.input :phone, wrapper: :vertical_input_group, label: false  do %>
        <span class="input-group-addon">Telefone</span>
      <%= f.input_field :phone, class: "form-control" %>
    <% end %>
  </div>
  <div class="form-inputs">
    <%= f.input :cell, wrapper: :vertical_input_group, label: false  do %>
        <span class="input-group-addon">Celular</span>
      <%= f.input_field :cell, class: "form-control" %>
    <% end %>
  </div>


  <%= simple_fields_for :address, @account.address do |a| %>
    <div class="form-inputs">
      <%= a.input :zip_code, wrapper: :vertical_input_group, label: false  do %>
          <span class="input-group-addon">CEP</span>
        <%= a.input_field :zip_code, class: "form-control icep" %>
      <% end %>
    </div>
    <div class="zip-spinner"></div>
    <div class="form-inputs">
      <%= a.input :street, wrapper: :vertical_input_group, label: false  do %>
          <span class="input-group-addon">Rua</span>
        <%= a.input_field :street, class: "form-control" %>
      <% end %>
    </div>
    <div class="form-inputs">
      <%= a.input :number, wrapper: :vertical_input_group, label: false  do %>
          <span class="input-group-addon">Número</span>
        <%= a.input_field :number, class: "form-control" %>
      <% end %>
    </div>
    <div class="form-inputs">
      <%= a.input :complement, wrapper: :vertical_input_group, label: false  do %>
          <span class="input-group-addon">Complemento</span>
        <%= a.input_field :complement, class: "form-control" %>
      <% end %>
    </div>
    <div class="form-inputs">
      <%= a.input :district, wrapper: :vertical_input_group, label: false  do %>
          <span class="input-group-addon">Bairro</span>
        <%= a.input_field :district, class: "form-control" %>
      <% end %>
    </div>
    <div class="form-inputs">
      <%= a.input :city, wrapper: :vertical_input_group, label: false  do %>
          <span class="input-group-addon">Cidade</span>
        <%= a.input_field :city, class: "form-control" %>
      <% end %>
    </div>
      <div class="form-inputs">
    <%= a.input :state, wrapper: :vertical_input_group, label: false  do %>
        <span class="input-group-addon">Cliente</span>
      <%=  a.input_field :state, as: :select,
                          collection: Account::STATES, prompt: "Selecione o estado",
                          class: 'form-control' %>
    <% end %>
  </div>
  <% end %><br/>

  <div class="btn-group">
    <%= link_to 'Cancelar', admin_accounts_path, class: 'btn btn-default' %>
    <%= f.button :submit, 'Salvar Cliente', class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/admin/accounts/edit.html.erb
<div class="page-header clearfix">
  <div class="pull-left">
    <h1><small>Editar Clientes</small></h1>
  </div>
</div>

<%= render 'form' %>

app/views/admin/accounts/index.html.erb
<div class="page-header clearfix">
  <div class="pull-left">
    <h1><small>Lista de Clientes</small></h1>
  </div>
</div>
<% if flash[:notice].present? %>
  <div class="alert alert-success" role="alert">
    <span class="glyphicon glyphicon-exclamation-sign" aria-hidden="true"></span>
    <span class="sr-only">Error:</span>
    <%= flash[:notice] %>
  </div>
<% end %>
<table class="table table-condensed table-bordered table-striped table-hover ">
  <thead>
    <tr>
      <th>Código</th>
      <th>Nome</th>
      <th>Endereço</th>
      <th style="width: 30px;">Editar</th>
    </tr>
  </thead>

  <tbody>
    <% @accounts.each do |c| %>
      <tr>
        <td><%= c.id %></td>
        <td><%= c.name %></td>
        <td><%= c.address.try(:to_sentence) %></td>
        <td><%= link_to 'Editar', edit_admin_account_path(c) %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<div class="btn-group">
  <%= link_to 'Cadastrar Novo Produto', new_admin_account_path, class: 'btn btn-primary'  %>
</div>

app/views/admin/accounts/new.html.erb
<div class="page-header clearfix">
  <div class="pull-left">
    <h1><small>Cadastro de Clientes</small></h1>
  </div>
</div>

<%= render 'form' %>

app/views/admin/budgets/_budget_item_fields.html.erb
<div class='nested-fields'>
    <div class="form-inputs">
      <%= f.input :product_id, wrapper: :vertical_input_group, label: false  do %>
          <span class="input-group-addon">Produto</span>
              <%=  f.input_field :product_id, as: :select,
                          collection: Product.find(:all).collect {|a| [a.name, a.id]},
                          :prompt => ' ', class: 'form-control' %>
      <% end %>
    </div>
    <div class="form-inputs">
      <%= f.input :amount, wrapper: :vertical_input_group, label: false  do %>
          <span class="input-group-addon">Quantidade</span>
        <%= f.input_field :amount, class: "form-control" %>
      <% end %>
    </div>
    <div class="form-inputs">
      <%= f.input :sub_total_price, wrapper: :vertical_input_group, label: false  do %>
          <span class="input-group-addon">Total do Produto</span>
        <%= f.input_field :sub_total_price, class: "form-control" %>
      <% end %>
    </div>
    <%= link_to_remove_association "Remove Produto", f, class: 'btn btn-danger' %>
    <hr><br/>
</div>

app/views/admin/budgets/_form.html.erb
<%= simple_form_for([:admin, @budget], wrapper: :horizontal_input_group,
        wrapper_mappings: {
          check_boxes: :horizontal_radio_and_checkboxes
        }) do |f| %>
  <% if @budget.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@account.errors.count, "error") %> prohibited this account from being saved:</h2>

      <ul>
      <% @account.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-inputs">
    <%= f.input :account_id, wrapper: :vertical_input_group, label: false  do %>
        <span class="input-group-addon">Cliente</span>
      <%=  f.input_field :account_id, as: :select,
                          collection: Account.find(:all).collect {|a| [a.name, a.id]},
                          :prompt => ' ', class: 'form-control' %>
    <% end %>
  </div>

  <div class="form-inputs">
    <%= f.input :media_kw, wrapper: :vertical_input_group, label: false  do %>
        <span class="input-group-addon">Média de KW</span>
      <%= f.input_field :media_kw, class: "form-control icpf" %>
    <% end %>
  </div>

  <h3>Produtos</h3>
  <div id='budget_items'>
    <%= f.simple_fields_for :budget_items do |budget_item| %>
      <%= render 'budget_item_fields', :f => budget_item %>
    <% end %>
    <div class='links'>
      <%= link_to_add_association 'Adicionar Produto', f, :budget_items, class: 'btn btn-primary' %>
    </div>
  </div><br/>


  <div class="btn-group">
    <%= link_to 'Cancelar', admin_budgets_path, class: 'btn btn-default' %>
    <%= f.button :submit, 'Salvar Produto', class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/admin/budgets/edit.html.erb
<div class="page-header clearfix">
  <div class="pull-left">
    <h1><small>Editar Orçamento</small></h1>
  </div>
</div>

<%= render 'form' %>

app/views/admin/budgets/index.html.erb
<div class="page-header clearfix">
  <div class="pull-left">
    <h1><small>Lista de Orçamentos</small></h1>
  </div>
</div>
<% if flash[:notice].present? %>
  <div class="alert alert-success" role="alert">
    <span class="glyphicon glyphicon-exclamation-sign" aria-hidden="true"></span>
    <span class="sr-only">Error:</span>
    <%= flash[:notice] %>
  </div>
<% end %>
<table class="table table-condensed table-bordered table-striped table-hover ">
  <thead>
    <tr>
      <th>Número Orçamento</th>
      <th>Orçamento para Cliente</th>
      <th>Orçamento para Cidade</th>
      <th>Valor Orçamento</th>
    </tr>
  </thead>

  <tbody>
    <% @budgets.each do |b| %>
      <tr>
        <td><%=link_to b.id, edit_admin_budget_path(b) %></td>
        <td><%=link_to b.account.name, edit_admin_budget_path(b) %></td>
        <td><%=link_to b.account.address.city, edit_admin_budget_path(b) %></td>
        <td>R<%=link_to number_to_currency(b.balance_total), edit_admin_budget_path(b) %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
  <%= link_to 'Novo Orçamento', new_admin_budget_path, :class => 'btn btn-primary'  %>

app/views/admin/budgets/new.html.erb
<div class="page-header clearfix">
  <div class="pull-left">
    <h1><small>Cadastro de Clientes</small></h1>
  </div>
</div>

<%= render 'form' %>

app/views/admin/products/_form.html.erb
<%= simple_form_for([:admin, @product], wrapper: :horizontal_input_group,
        wrapper_mappings: {
          check_boxes: :horizontal_radio_and_checkboxes
        }) do |f| %>
        <% if flash[:error].present? %>
          <div class="alert alert-danger" role="alert">
            <span class="glyphicon glyphicon-exclamation-sign" aria-hidden="true"></span>
            <span class="sr-only">Error:</span>
            <%= flash[:error] %>
          </div>
        <% end %>
  <div class="form-inputs">
    <%= f.input :name, wrapper: :vertical_input_group, hint: "Obrigatório", label: false  do %>
    <span class="input-group-addon">Nome</span>
      <%= f.input_field :name, class: "form-control" %>
    <% end %>

    <%= f.input :description, wrapper: :vertical_input_group, label: false  do %>
    <span class="input-group-addon">Descrição</span>
      <%= f.input_field :description, class: "form-control", as: :text %>
    <% end %>

    <%= f.input :number_references, wrapper: :vertical_input_group, label: false  do %>
    <span class="input-group-addon">Registro</span>
      <%= f.input_field :number_references, class: "form-control" %>
    <% end %>

    <%= f.input :balance, wrapper: :vertical_input_group, label: false  do %>
    <span class="input-group-addon">Valor</span>
      <%= f.input_field :balance, class: "form-control" %>
    <% end %>

    <hr>

  </div>

  <div class="btn-group">
    <%= link_to 'Cancelar', admin_products_path, class: 'btn btn-default' %>
    <%= f.button :submit, 'Salvar Produtos', class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/admin/products/edit.html.erb
<div class="page-header clearfix">
  <div class="pull-left">
    <h1><small>Editar Produtos</small></h1>
  </div>
</div>

<%= render 'form' %>

app/views/admin/products/index.html.erb
<div class="page-header clearfix">
  <div class="pull-left">
    <h1><small>Lista de Produtos</small></h1>
  </div>
</div>
<% if flash[:notice].present? %>
  <div class="alert alert-success" role="alert">
    <span class="glyphicon glyphicon-exclamation-sign" aria-hidden="true"></span>
    <span class="sr-only">Error:</span>
    <%= flash[:notice] %>
  </div>
<% end %>
<table class="table table-condensed table-bordered table-striped table-hover ">
  <thead>
    <tr>
      <th>Código</th>
      <th>Nome</th>
      <th>Descrição</th>
      <th>Número de Referência</th>
      <th>Valor</th>
      <th style="width: 30px;">Editar</th>
    </tr>
  </thead>

  <tbody>
    <% @products.each do |p| %>
      <tr>
        <td><%=link_to p.id, admin_product_path(p) %></td>
        <td><%=link_to p.name, admin_product_path(p) %></td>
        <td><%=link_to p.description, admin_product_path(p) %></td>
        <td><%=link_to p.number_references, admin_product_path(p) %></td>
        <td><%=link_to number_to_currency(p.balance), admin_product_path(p) %></td>
        <td><%=link_to 'Editar', edit_admin_product_path(p) %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
  <%= link_to 'Cadastrar Novo Produto', new_admin_product_path, :class => 'btn btn-primary'  %>

app/views/admin/products/new.html.erb
<div class="page-header clearfix">
  <div class="pull-left">
    <h1><small>Cadastro de Produtos</small></h1>
  </div>
</div>

<%= render 'form' %>

app/views/admin/products/show.html.erb
<div class="page-header clearfix">
  <div class="pull-left">
    <h1><small>Produto <%= @product.name %> </small></h1>
  </div>
</div>
<table class="table table-condensed table-bordered table-striped table-hover ">
  <thead>
    <tr>
      <th>Código</th>
      <th>Nome</th>
      <th>Descrição</th>
      <th>Número de Referência</th>
    </tr>
  </thead>

  <tbody>
    <tr>
      <td><%= @product.id %></td>
      <td><%= @product.name %></td>
      <td><%= @product.description %></td>
      <td><%= @product.number_references %></td>
    </tr>
  </tbody>
</table>

<div class="btn-group">
  <%= link_to 'Voltar', admin_products_path, class: 'btn btn-default' %>
</div>

app/views/admin/welcomes/index.html.erb
    <div id="container" style="min-width: 310px; height: 400px; margin: 0 auto"></div>
      <style type="text/css">
        ${demo.css}
      </style>
      <script type="text/javascript">
        $(function () {
            chart = new Highcharts.Chart({
                chart: {
                    renderTo: 'container',
                    type: 'column'
                },
                title: {
                    text: 'Monthly Average Rainfall'
                },
                subtitle: {
                    text: 'Source: WorldClimate.com'
                },
                xAxis: {
                    categories: [
                        'Jan',
                        'Feb',
                        'Mar',
                        'Apr',
                        'May',
                        'Jun',
                        'Jul',
                        'Aug',
                        'Sep',
                        'Oct',
                        'Nov',
                        'Dec'
                    ],
                    crosshair: true
                },
                yAxis: {
                    min: 0,
                    title: {
                        text: 'Rainfall (mm)'
                    }
                },
                tooltip: {
                    headerFormat: '<span style="font-size:10px">{point.key}</span><table>',
                    pointFormat: '<tr><td style="color:{series.color};padding:0">{series.name}: </td>' +
                        '<td style="padding:0"><b>{point.y:.1f} mm</b></td></tr>',
                    footerFormat: '</table>',
                    shared: true,
                    useHTML: true
                },
                plotOptions: {
                    column: {
                        pointPadding: 0.2,
                        borderWidth: 0
                    }
                },
                series: [{
                    name: 'Tokyo',
                    data: [49.9, 71.5, 106.4, 129.2, 144.0, 176.0, 135.6, 148.5, 216.4, 194.1, 95.6, 54.4]

                }, {
                    name: 'New York',
                    data: [83.6, 78.8, 98.5, 93.4, 106.0, 84.5, 105.0, 104.3, 91.2, 83.5, 106.6, 92.3]

                }, {
                    name: 'London',
                    data: [48.9, 38.8, 39.3, 41.4, 47.0, 48.3, 59.0, 59.6, 52.4, 65.2, 59.3, 51.2]

                }, {
                    name: 'Berlin',
                    data: [42.4, 33.2, 34.5, 39.7, 52.6, 75.5, 57.4, 60.4, 47.6, 39.1, 46.8, 51.1]

                }]
            });
        });
    </script>
  </div>

app/views/layouts/admin/application.html.erb
<html>
<head>
  <title>Nova Hera Solar</title>
  <script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jquery/1.8.2/jquery.min.js"></script>
  <%= javascript_include_tag 'admin/application' %>
  <%= csrf_meta_tags %>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css">
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js"></script>

  <%= stylesheet_link_tag 'admin/application', media: 'all' %>

</head>
<body>

  <div id="wrapper" style='width: 100%;'>
      <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
          <div class="navbar-header">
              <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
                  <span class="sr-only">Toggle navigation</span>
                  <span class="icon-bar"></span>
                  <span class="icon-bar"></span>
                  <span class="icon-bar"></span>
              </button>
              <div>
                <%= image_tag 'inovacao_solar.jpg', :size => '70x45'%>
                <a class="navbar-brand" href="/admin/products">Nova Hera Solar</a>
              </div>
          </div>

          <ul class="nav navbar-right top-nav">
              <li class="dropdown">
                  <a href="#" class="dropdown-toggle" data-toggle="dropdown"><i class="fa fa-user">
                    </i> John Smith <b class="caret"></b></a>
                  <ul class="dropdown-menu">
                      <li>
                          <a href="#"><i class="fa fa-fw fa-gear"></i> Settings</a>
                      </li>
                      <li class="divider"></li>
                      <li>
                          <a href="#"><i class="fa fa-fw fa-power-off"></i> Log Out</a>
                      </li>
                  </ul>
              </li>
          </ul>
          <div class="collapse navbar-collapse navbar-ex1-collapse">
              <ul class="nav navbar-nav side-nav">
                  <li>
                    <%= link_to ' Dashboard', admin_welcomes_path, class:"fa fa-dashboard" %>
                  </li>
                  <li>
                    <%= link_to ' Clientes', admin_accounts_path, class:"fa fa-user-plus" %>
                  </li>
                  <li>
                    <%= link_to ' Produtos', admin_products_path, class:"fa fa-cubes" %>
                  </li>
                  <li>
                    <%= link_to ' Orçamento', admin_budgets_path, class:"fa fa-cc" %>
                  </li>
                  <li>
                    <%= link_to ' Dados de Geração mensal', admin_products_path, class:"fa fa-bar-chart" %>
                  </li>
              </ul>
          </div>
      </nav>
      <div class="row">
          <div class="col-lg-12">
              <div class="panel panel-default">
                  <div class="panel-body">
                    <%= yield%>
                  </div>
              </div>
          </div>
      </div>
  </div>
</body>

</html>